name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:

jobs:
  check:
    strategy:
      matrix:
        target:
          - thumbv6m-none-eabi
          - thumbv7m-none-eabi
          - x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use the latest stable release
        run: rustup update stable && rustup default stable
      - name: Install compilation target
        run: rustup target add ${{ matrix.target }}
      - run: cargo check --target ${{ matrix.target }}

  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use the latest stable release
        run: rustup update stable && rustup default stable
      - run: cargo fmt --check
      - run: cargo clippy --all-targets -- -D warnings
